config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  get "contacts/new"
  get "contacts/create"
  # Webhook resources and job trigger for Stripe activity
  post "webhooks", to: "webhooks#create"
  # Admin routes
  get "admin", to: "admin#dashboard"

  # Visitor routes
  get "home", to: "pages#home"
  get "about", to: "pages#about"
  get "shop", to: "pages#shop"

  # Products routes
  resources :products, only: [ :new, :create, :edit, :index, :destroy ]
  get "products/:id", to: "products#show"
  patch "products/:id", to: "products#update"

  # Order routes
  resources :orders, only: [ :create, :index, :show ]

  # Shipments routes
  resources :shipments, only: [ :create, :index, :show ]

  # Cart routes
  resource :cart, only: [ :show ] do
    post "add_item/:product_id", to: "carts#add_item", as: :add_item
    delete "remove_item/:product_id", to: "carts#remove_item", as: :remove_item
  end

  # Payments with Stripe
  get "checkout", to: "checkout#new"
  get "checkout/success", to: "checkout#success"

  # Shipping controller routes(Shippo API)
  post "shipping_options", to: "shipping_options#create"

  # Contact Forms controller(Handles 'Contact Us' submissions)
  resources :contact_forms, only: [ :new, :create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/contact_form.rb
class ContactForm
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :email, :message, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/order.rb
class Order < ApplicationRecord
  enum :status, { pending: 0, paid: 1, canceled: 2 }
  has_many :order_items, dependent: :destroy
  has_one :shipment, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, :category, :description, :price, :stock, presence: true

  after_update :check_out_of_stock
  after_update :update_stripe_product
  after_update :update_stripe_price
  before_destroy :archive_stripe_product, prepend: true

  has_many :cart_items, dependent: :destroy
  has_many :order_items
  has_one_attached :main_image do |attachable|
    attachable.variant :thumb, resize_to_limit: [ 100, 100 ]
    attachable.variant :card_image, resize_to_limit: [ 500, 500 ]
  end
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [ 100, 100 ]
    attachable.variant :card_image, resize_to_limit: [ 500, 500 ]
  end


  private

  # Toggles out-of-stock state of products
  def check_out_of_stock
    if self.stock < 1 && !self.out_of_stock

      self.update!(out_of_stock: true)

    elsif self.stock > 0 && self.out_of_stock

      self.update!(out_of_stock: false)

    else
      nil
    end
  end

  # Updates title and description of product if change has occurred
  def update_stripe_product
    return unless stripe_product_id.present?
    if saved_change_to_title? || saved_change_to_description?
      StripeService::UpdateProduct.call(self)
    end
  end

  # Adds new price object to Stripe product if change detected
  def update_stripe_price
    return unless stripe_product_id.present?
    if saved_change_to_price?
      StripeService::UpdatePrice.call(self)
    end
  end

  # Archives Stripe Product (triggered on destroy)
  def archive_stripe_product
    Stripe::Product.update("#{self.stripe_product_id}", { active: false })
  rescue Stripe::StripeError => e
    Rails.logger.error "Error archiving Stripe Product: #{e.message}"
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :order
  enum :tracking_status, { unknown: 0, failure: 1, returned: 3, delivered: 4, transit: 5, pre_transit: 6 }
end

app/models/shipping_rate.rb
class ShippingRate < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/models/webhook_event.rb
class WebhookEvent < ApplicationRecord
  after_create_commit :process_webhook_event

  private

  def process_webhook_event
    CheckoutSessionProcessingJob.perform_later(self)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shipping_helper.rb
module ShippingHelper
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/admin/_accordion.html.erb
<!-- app/views/admin/_accordion.html.erb -->

<div class="accordion w-100" id="accordionAdmin">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed bg-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Products
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionAdmin">
      <div class="accordion-body">
        <div class="list-group list-group-flush" id="admin_options_list">
          <%= link_to "View Products", products_path, class: "list-group-item list-group-item-action", data: { turbo_frame: "adminOptions" } %>
          <%= link_to "Add Product", new_product_path, class: "list-group-item list-group-item-action", data: { turbo_frame: "adminOptions" } %>
        </div>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed bg-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Orders
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionAdmin">
      <div class="accordion-body">
        <div class="list-group list-group-flush" id="admin_options_list">
          <%= link_to "View Orders", orders_path, class: "list-group-item list-group-item-action", data: { turbo_frame: "adminOptions" } %>
        </div>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed bg-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Shipments
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionAdmin">
      <div class="accordion-body">
        <div class="list-group list-group-flush" id="admin_options_list">
          <a href="#" class="list-group-item list-group-item-action">View All</a>
          <a href="#" class="list-group-item list-group-item-action">Purchase Labels</a>
        </div>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed bg-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
        Emails
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" data-bs-parent="#accordionAdmin">
      <div class="accordion-body">
        <div class="list-group list-group-flush" id="admin_options_list">
          <a href="#" class="list-group-item list-group-item-action">View All</a>
          <a href="#" class="list-group-item list-group-item-action">Send New</a>
        </div>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed bg-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
        Reviews
      </button>
    </h2>
    <div id="collapseFive" class="accordion-collapse collapse" data-bs-parent="#accordionAdmin">
      <div class="accordion-body">
        <div class="list-group list-group-flush" id="admin_options_list">
          <a href="#" class="list-group-item list-group-item-action">View All</a>
          <a href="#" class="list-group-item list-group-item-action">Add Review</a>
        </div>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed bg-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
        Refunds
      </button>
    </h2>
    <div id="collapseSix" class="accordion-collapse collapse" data-bs-parent="#accordionAdmin">
      <div class="accordion-body">
        <div class="list-group list-group-flush" id="admin_options_list">
          <a href="#" class="list-group-item list-group-item-action">View All</a>
          <a href="#" class="list-group-item list-group-item-action">Add New</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/dashboard.html.erb
<div id="adminDashboard" class="container-fluid">
  <div class="row h-100 flex-wrap">
    
    <aside class="col-md-3 col-xl-2 d-flex flex-column">
        <h5>Welcome <small><%# @admin.email %></small></h5>
        <div class="d-flex pb-3 mt-5 flex-column justify-content-center align-items-center gap-2">
          <%= render partial: "accordion" %>
        </div>
    </aside>

    <main class="col-md-9 col-xl-8" >
      <turbo-frame id="adminOptions" ></turbo-frame>
    </main>

      <aside class="col-0 col-xl-2">
      </aside>


  </div>
</div>

<%= javascript_include_tag 'custom/active_list_item.js' %>

app/views/admin/products.html.erb
<h1>Products</h1>

app/views/layouts/_alert.html.erb
<% if flash.any? %>
  <div class="container-fluid d-flex flex-column align-items-center p-0 m-0">
  <% flash.each do |type, msg| %>
    <div class="alert alert-<%= type.to_s %> m-0 w-100 text-center"><%= msg %></div>
  <% end %>
  </div>
<% end %>

app/views/layouts/_cart_button.html.erb
<!-- app/views/pages/shop_partials/_cart_button.html.erb

  Fixed button to guide user to cart review and checkout

-->
<%= turbo_frame_tag "cart_button_frame" do %>
  <% if cart_count > 0 %>
    <button class="rounded-circle shadow cart-button <%= animation_type %>" type="button" data-bs-toggle="collapse" data-bs-target="#cartDetails" aria-expanded="false" aria-controls="cartDetails">
      <div class="cart-wrapper p-2">
        <i class="bi bi-cart fs-3 text-white"></i>
        <%= turbo_frame_tag "cart_counter" do %>
          <%= render "carts/cart_counter" %>
        <% end %>
      </div>
    </button>
  <% end %>
<% end %>

app/views/layouts/_cart_counter.html.erb
<!-- app/layouts/_cart_counter.html.erb

  Display current number of cart items belonging to session cart

-->
<% if cart_count > 0 %>
  <span class="cart-counter">
    <%= cart_count %>
  </span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Zold Ceramics" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Zold Ceramics">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# Allow page specific javascripts to be loaded in the head as needed %>
    <%= yield(:page_scripts) %>
  </head>

  <body class="d-flex flex-column justify-content-between min-vh-100 bg-light">  
      <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
          <button class="navbar-toggler my-1" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a href="<%= home_path %>" class="navbar-brand">Zold Ceramics</a>
          <div class="collapse justify-content-end navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mb-0" data-controller="active-nav" data-active-nav-active-class="active">
              <li class="nav-item mx-2">
                <a class="nav-link" data-active-nav-target="navLink" aria-current="page" href="<%= home_path %>">Home</a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link" href="<%= home_path + "#about" %>">About</a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link"  href="<%= home_path + "#contact" %>">Contact</a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link" data-active-nav-target="navLink" href="<%= shop_path %>">Shop</a>
              </li>
            </ul>
          </div>
        </div>
        </nav>
      </header>

      <main>
        <!-- Cart Summary Collapse and Button -->
        <%= render "carts/cart_summary", show: "hidden", cart: @cart %>
        <%= render "layouts/cart_button", animation_type: nil %>
        <!-- Page Content -->
        <%= yield %>
      </main>

      <div class="container">
      <footer class=" d-flex flex-wrap justify-content-between align-items-center py-1 my-1 border-top">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-2 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1" aria-label="Bootstrap">
            <i class="bi bi-cup-hot-fill h3 mb-0"></i>
          </a>
        </div>
        <span class="mb-3 mb-md-0 text-body-secondary">© 2025 Zold Ceramics</span>
        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
          <li class="ms-3">
            <a class="text-body-secondary" href="#" aria-label="Instagram">
              <i class="bi bi-instagram"></i>
            </a>
          </li>
          <li class="ms-3">
            <a class="text-body-secondary" href="#" aria-label="Facebook">
              <i class="bi bi-facebook"></i>
            </a>
          </li>
        </ul>
      </footer>
    </div>
  </body>
</html>

app/views/pages/shop_partials/_cart_button.html.erb
<!-- app/views/pages/shop_partials/_cart_button.html.erb

  Fixed button to guide user to cart review and checkout

-->

<div class="cart-button-container d-inline-flex align-items-start gap-2">

  <div class="collapse collapse-horizontal" id="cartDetails">
    <div class="card" style="width: 200px;">
      <div class="card-body">
        <%= button_to "View Cart", cart_path, method: :get, class: "btn btn-outline-warning" %>
        <%= button_to "Checkout", cart_path, method: :get, class: "btn btn-warning" %>
      </div>
    </div>
  </div>

  <button class="btn btn-warning py-2 cart-wrapper" style="border-radius: 50%"type="button" data-bs-toggle="collapse" data-bs-target="#cartDetails" aria-expanded="false" aria-controls="cartDetails">
    <i class="bi bi-cart2 h4 text-white"></i>
    <%= turbo_frame_tag "cart_counter" do %>
      <%= render "carts/cart_counter" %>
    <% end %>
  </button>

</div>

app/views/pages/shop_partials/_hero.html.erb
<!-- Hero Photo -->
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col p-0">
      <div class="card hero-image-container border-0 d-flex flex-wrap">
        <%= image_tag "1000014593.jpg", class: "card-img hero-image rounded-0 img-fluid opacity-75", alt: "Background image with three handmade mugs" %>
        <div class="card-img-overlay heroOverlay d-flex flex-column justify-content-center gap-5 align-items-center p-lg-5">
          <div class="heroText">
            <p class="card-title text-center text-light display-1" style="text-shadow: 1px 0px 5px gray;">
              Drink. Dine. Decorate.
            </p>
      </div>
    </div>
  </div>
</div>

app/views/pages/shop_partials/_product_card.html.erb
  <div class="container-fluid p-0">
    <div class="row flex-wrap">

      <% if products.any? %>
        <% carousel_counter_number = 0 %> <!-- Allow each control to have different id -->
        <% products.each do |product| %>
          <!-- CAROUSEL -->
          <div class="card my-1 rounded-0 my-sm-0 p-0 shadow d-flex justify-content-between col-12 col-sm-6 col-xl-4">
            <div class="card-img rounded-0">

              <%= render "pages/shop_partials/product_image_carousel", carousel_counter_number: carousel_counter_number, product: product %>

            </div>
            <!-- Out Of Stock overlay -->
            <% if product.out_of_stock %>
              <div class="out_of_stock_overlay">
                <span class="badge fs-5">OUT OF STOCK</span>
              </div>
            <% end %>
            <!-- Product Info -->
            <div class="card-body d-flex flex-column justify-content-between pb-2 pb-lg-3">
              <div>
              <h5 class="card-title"><%= product.title %></h5>
              <p class="card-text mb-auto"><%= product.description %></p>
              </div>
              <div>
              <% if !product.out_of_stock %>
                <p class="card-text mt-2"><b>Price: </b><%= number_to_currency(product.price).to_s %></p>
                <%= form_with url: add_item_cart_path(product_id: product.id), class: "d-flex justify-content-between", method: :post do |form| %>
                  <div class="container w-100 d-flex justify-content-between">
                    <%= form.submit "Add to cart", class: "btn btn-warning" %>
                    <%= form.number_field :num_of_items, class: "form-control w-25", value: 1, min: 1, max: product.stock, step: 1, id: "product_stock" %>
                  </div>
                <% end %>
              <% end %>
              </div>
            </div>
          </div>
          <% carousel_counter_number += 1 %>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/pages/shop_partials/_product_image_carousel.html.erb
<div id="carousel<%= carousel_counter_number.to_s %>" class="carousel slide">
 <div class="carousel-inner">
  <div class="carousel-item active">
    <% if !product.main_image.attached? %>
      <% main_image_url = "1000014596.jpg" %>
    <% else %>
      <% main_image_url = product.main_image %>
    <% end %>
    <%= image_tag main_image_url, class: "card-image", alt: "" %>
  </div>

  <% if product.images.any? %>
    <% product.images.each do |image| %>
      <div class="carousel-item">
        <%= image_tag image, class: "d-block w-100", alt: "" %>
      </div>
    <% end %>
  <% end %>
 </div>
 <button class="carousel-control-prev" type="button" data-bs-target="#carousel<%= carousel_counter_number.to_s %>" data-bs-slide="prev">
   <span class="carousel-control-prev-icon" aria-hidden="true"></span>
   <span class="visually-hidden">Previous</span>
 </button>
 <button class="carousel-control-next" type="button" data-bs-target="#carousel<%= carousel_counter_number.to_s %>" data-bs-slide="next">
   <span class="carousel-control-next-icon" aria-hidden="true"></span>
   <span class="visually-hidden">Next</span>
 </button>
</div>

app/views/pages/shop_partials/_product_type_banner.html.erb
<button class="btn card-img product-category-card w-100 btn-secondary" data-bs-toggle="collapse" data-bs-target="#collapse<%= card_number %>" aria-expanded="false" aria-controls="collapse<%= card_number %>">
  <div class="display-3 text-light" id="headingOne" ><%= product_category %></div>
</button>
<div id="collapse<%= card_number %>" class="collapse" aria-labelledby="heading<%= card_number %>" data-bs-parent="#accordion">
  <div class="card-body">
    <%= render "products/partial/product_card", products: products %>
  </div>
</div>

app/views/shared/_banner_1.html.erb
<div class="container-fluid">
  <div class="row align-items-center bg-secondary" style="height:250px">
    <div class="col-xxl-5 col-xl-6 col-lg-8 col-sm-9 container">
          <h2 class="text-dark h2">The warmth of the kiln</h2>
          <h1 class="text-white text-end">...in every sip</h1>
    </div>
  </div>
</div>