config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  get "contacts/new"
  get "contacts/create"
  # Webhook resources and job trigger for Stripe activity
  post "webhooks", to: "webhooks#create"
  # Admin routes
  get "admin", to: "admin#dashboard"

  # Visitor routes
  get "home", to: "pages#home"
  get "about", to: "pages#about"
  get "shop", to: "pages#shop"

  # Products routes
  resources :products, only: [ :new, :create, :edit, :index, :destroy ]
  get "products/:id", to: "products#show"
  patch "products/:id", to: "products#update"

  # Order routes
  resources :orders, only: [ :create, :index, :show ]

  # Shipments routes
  resources :shipments, only: [ :create, :index, :show ]

  # Cart routes
  resource :cart, only: [ :show ] do
    post "add_item/:product_id", to: "carts#add_item", as: :add_item
    delete "remove_item/:product_id", to: "carts#remove_item", as: :remove_item
  end

  # Payments with Stripe
  get "checkout", to: "checkout#new"
  get "checkout/success", to: "checkout#success"

  # Shipping controller routes(Shippo API)
  post "shipping_options", to: "shipping_options#create"

  # Contact Forms controller(Handles 'Contact Us' submissions)
  resources :contact_forms, only: [ :new, :create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/contact_form.rb
class ContactForm
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :email, :message, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/order.rb
class Order < ApplicationRecord
  enum :status, { pending: 0, paid: 1, canceled: 2 }
  has_many :order_items, dependent: :destroy
  has_one :shipment, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, :category, :description, :price, :stock, presence: true

  after_update :check_out_of_stock
  after_update :update_stripe_product
  after_update :update_stripe_price
  before_destroy :archive_stripe_product, prepend: true

  has_many :cart_items, dependent: :destroy
  has_many :order_items
  has_one_attached :main_image do |attachable|
    attachable.variant :thumb, resize_to_limit: [ 100, 100 ]
    attachable.variant :card_image, resize_to_limit: [ 500, 500 ]
  end
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [ 100, 100 ]
    attachable.variant :card_image, resize_to_limit: [ 500, 500 ]
  end


  private

  # Toggles out-of-stock state of products
  def check_out_of_stock
    if self.stock < 1 && !self.out_of_stock

      self.update!(out_of_stock: true)

    elsif self.stock > 0 && self.out_of_stock

      self.update!(out_of_stock: false)

    else
      nil
    end
  end

  # Updates title and description of product if change has occurred
  def update_stripe_product
    return unless stripe_product_id.present?
    if saved_change_to_title? || saved_change_to_description?
      StripeService::UpdateProduct.call(self)
    end
  end

  # Adds new price object to Stripe product if change detected
  def update_stripe_price
    return unless stripe_product_id.present?
    if saved_change_to_price?
      StripeService::UpdatePrice.call(self)
    end
  end

  # Archives Stripe Product (triggered on destroy)
  def archive_stripe_product
    Stripe::Product.update("#{self.stripe_product_id}", { active: false })
  rescue Stripe::StripeError => e
    Rails.logger.error "Error archiving Stripe Product: #{e.message}"
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :order
  enum :tracking_status, { unknown: 0, failure: 1, returned: 3, delivered: 4, transit: 5, pre_transit: 6 }
end

app/models/shipping_rate.rb
class ShippingRate < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/models/webhook_event.rb
class WebhookEvent < ApplicationRecord
  after_create_commit :process_webhook_event

  private

  def process_webhook_event
    CheckoutSessionProcessingJob.perform_later(self)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_product, only: [ :add_item, :remove_item ]

  # Load cart items for display
  def show
    @order_total = 0
    if @cart.cart_items
      @cart.cart_items.each do |item|
        @order_total += item.product.price * item.quantity
      end
    end
  end
  # Add product to cart
  def add_item
    amount_to_purchase = params[:num_of_items]
    new_item = @cart.cart_items.find_or_create_by(product_id: @product.id)
    new_item.quantity += amount_to_purchase.to_i
    new_item.save!

    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: [
        turbo_stream.update("cart_counter", partial: "carts/cart_counter"),
        turbo_stream.update(
          "cart_button_frame",
          partial: "layouts/cart_button",
          locals: { animation_type: "bounce-cart" }),
        turbo_stream.update(
          "cart_summary_frame",
          partial: "carts/cart_summary",
          locals: { show: "hidden", cart: @cart }
        )
        ]
      }
    end
  end
  # Remove product from cart
  def remove_item
    @cart.cart_items.delete_by(product_id: @product.id)

    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: [
          turbo_stream.update("cart_counter", partial: "carts/cart_counter"),
          turbo_stream.update(
            "cart_summary_frame",
            partial: "carts/cart_summary",
            locals: { show: "show", cart: @cart }),
        turbo_stream.update(
          "cart_button_frame",
          partial: "layouts/cart_button",
          locals: { animation_type: nil })
        ]
      }
    end
  end

  private

  def set_product
  @product = Product.find(params[:product_id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/helpers/shipping_helper.rb
module ShippingHelper
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/carts/_cart_counter.html.erb
<!-- app/carts/_cart_counter.html.erb

  Display current number of cart items belonging to session cart
-->
<% if cart_count > 0 %>
  <span class="cart-counter">
    <%= cart_count %>
  </span>
<% end %>

app/views/carts/_cart_items.html.erb
<!-- app/views/carts/_cart_items.html.erb
  Cart item display card
-->
<ul class="list-group shopping-cart-list">
  <% order_total = 0 %>
  <% if cart.cart_items.any? %>
    <% cart.cart_items.each do |item| %>
      <% order_total += (item.product.price * item.quantity) %>
      <% product = Product.find_by(id: item.product_id) %>
      <% if product %>
        <li class="list-group-item container-fluid">
          <div class="row align-items-center">
            <div class="col-12 col-sm-3">
              <%= image_tag product.main_image, class: "cart-image" %>
            </div>
            <div class="col-8 col-sm-6">
              <p class="fs-5 mb-1 mt-2 mt-sm-0"><b><%= product.title %></b></p>
              <p class="mb-1">
                <b>Qty: </b><%= item.quantity %>
              </p>
              <p class="mb-1"><b>Total: </b><%= number_to_currency(product.price * item.quantity) %></p>
            </div>
            <div class="col-4 col-sm-3 text-center">
              <%= button_to remove_item_cart_path(item.product_id), class: "btn", method: :delete do %>
                <i class="bi bi-trash3 text-danger fs-2"></i>
              <% end %>
            </div>
          </div>
        </li>
      <% else %>
        <div class="alert alert-danger" role="alert">
          This product is no longer available. Check back with us again!
        </div>
      <% end %>
    <% end %>
  <% end %>
  <li class="list-group-item text-end">
    <b>Cart Total: </b> <%= number_to_currency(order_total) %>
  </li>
</ul>

app/views/carts/_cart_summary.html.erb
<!-- app/views/carts/_cart_summary.html.erb -->
<%= turbo_frame_tag "cart_summary_frame" do %>
  <!-- Hide if no cart items -->
  <% if cart_count > 0 %>
    <!-- Fixed-Width Container for smooth slide-in transition -->
    <div class="cart-summary-container d-inline-flex align-items-end">
      <div class="collapse collapse-horizontal <%= show %> mb-5" id="cartDetails">
        <div class="card rounded-end-0 border-end-0 shadow-lg cart-preview-card">
          <h3 class="cart-summary-title text-center text-white p-2">Cart Summary</h3>
          <!-- Cart Items List -->
          <div class="container rounded-start bg-white">
            <ul class="list-group list-group-flush cart-summary-list">
              <!-- Calculate total --> 
              <% cart_total = 0 %>
              <% @cart.cart_items.each do |item| %>
                <% cart_total += item.quantity * item.product.price %>
                <!-- Item Details -->
                <li class="list-group-item d-flex px-1 justify-content-between opacity-75">
                  <!-- Item Delete Button and Title -->
                  <div class="cart-summary-item-title">
                    <%= button_to remove_item_cart_path(item.product_id), class: "btn rounded-circle pt-2 ps-1 border-0 m-0", method: :delete do %>
                      <i class="bi bi-x-circle text-danger opacity-75 fs-5"></i>
                    <% end %>
                    <%= item.product.title %>
                  </div>
                  <!-- Item Quantity and Price -->
                  <div class="cart-summary-amounts">
                    <div class="w-25 text-start">x<%= item.quantity %></div>
                    <div class="w-75"><%= number_to_currency(item.product.price) %></div>
                  </div>
                </li>
              <% end %>
              <!-- Cart Total -->
            </ul>
            <!-- Cart Nav Options -->
            <h5 class="card-title border-top border-2 fs-6 opacity-75 p-3 text-end">Total: <%= number_to_currency(cart_total) %></h5>
            <div class="card-body d-flex justify-content-between">
              <button 
                class="btn text-white btn-info"
                type="button" 
                data-bs-toggle="collapse"
                data-bs-target="#cartDetails"
                aria-expanded="true"
                aria-controls="cartDetails">
                Hide Cart
              </button>
              <%= button_to "Checkout", cart_path, method: :get, class: "btn border-3 btn-secondary text-white" %>
            </div>
          </div>
        </div>
      </div>
    </div>

  <% end %>
<% end %>

app/views/carts/show.html.erb
<div class="container-fluid">
  <div class="row flex-wrap">

    <aside class="col"></aside>

    <!-- Shopping Cart -->
    <main class="col-12 col-md-10 col-xxl-8 p-0">

        <div class="card bg-secondary shadow shopping-cart-card border-0">
          <h4 class="card-title text-center mt-2 text-white">Cart Details</h4>
          <div class="card-body px-1 px-sm-3 mx-md-3 rounded bg-white shopping-cart-body overflow-auto">

            <%= render "layouts/alert" %>

            <!-- Shopping Cart List Details -->
            <%= turbo_frame_tag "cart_items_card" do %>
              <%= render "cart_items", cart: @cart %>
            <% end %>

          </div>
          <!-- Checkout Button -->
          <div class="container-fluid d-flex justify-content-center align-items-center py-1">
            <%= button_to "Checkout", orders_path,
            class: "btn btn-warning",
            method: :post,
            data: { turbo: false } %>
          </div>
        </div>
    </main>

    <aside class="col"></aside>

  </div>
</div>