config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  get "contacts/new"
  get "contacts/create"
  # Webhook resources and job trigger for Stripe activity
  post "webhooks", to: "webhooks#create"
  # Admin routes
  get "admin", to: "admin#dashboard"

  # Visitor routes
  get "home", to: "pages#home"
  get "about", to: "pages#about"
  get "shop", to: "pages#shop"

  # Products routes
  resources :products, only: [ :new, :create, :edit, :index, :destroy ]
  get "products/:id", to: "products#show"
  patch "products/:id", to: "products#update"

  # Order routes
  resources :orders, only: [ :create, :index, :show ]

  # Shipments routes
  resources :shipments, only: [ :create, :index, :show ]

  # Cart routes
  resource :cart, only: [ :show ] do
    post "add_item/:product_id", to: "carts#add_item", as: :add_item
    delete "remove_item/:product_id", to: "carts#remove_item", as: :remove_item
  end

  # Payments with Stripe
  get "checkout", to: "checkout#new"
  get "checkout/success", to: "checkout#success"

  # Shipping controller routes(Shippo API)
  post "shipping_options", to: "shipping_options#create"

  # Contact Forms controller(Handles 'Contact Us' submissions)
  resources :contact_forms, only: [ :new, :create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/contact_form.rb
class ContactForm
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :email, :message, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/order.rb
class Order < ApplicationRecord
  enum :status, { pending: 0, paid: 1, canceled: 2 }
  has_many :order_items, dependent: :destroy
  has_one :shipment, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, :category, :description, :price, :stock, presence: true

  after_update :check_out_of_stock
  after_update :update_stripe_product
  after_update :update_stripe_price
  before_destroy :archive_stripe_product, prepend: true

  has_many :cart_items, dependent: :destroy
  has_many :order_items
  has_one_attached :main_image do |attachable|
    attachable.variant :thumb, resize_to_limit: [ 100, 100 ]
    attachable.variant :card_image, resize_to_limit: [ 500, 500 ]
  end
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [ 100, 100 ]
    attachable.variant :card_image, resize_to_limit: [ 500, 500 ]
  end


  private

  # Toggles out-of-stock state of products
  def check_out_of_stock
    if self.stock < 1 && !self.out_of_stock

      self.update!(out_of_stock: true)

    elsif self.stock > 0 && self.out_of_stock

      self.update!(out_of_stock: false)

    else
      nil
    end
  end

  # Updates title and description of product if change has occurred
  def update_stripe_product
    return unless stripe_product_id.present?
    if saved_change_to_title? || saved_change_to_description?
      StripeService::UpdateProduct.call(self)
    end
  end

  # Adds new price object to Stripe product if change detected
  def update_stripe_price
    return unless stripe_product_id.present?
    if saved_change_to_price?
      StripeService::UpdatePrice.call(self)
    end
  end

  # Archives Stripe Product (triggered on destroy)
  def archive_stripe_product
    Stripe::Product.update("#{self.stripe_product_id}", { active: false })
  rescue Stripe::StripeError => e
    Rails.logger.error "Error archiving Stripe Product: #{e.message}"
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :order
  enum :tracking_status, { unknown: 0, failure: 1, returned: 3, delivered: 4, transit: 5, pre_transit: 6 }
end

app/models/shipping_rate.rb
class ShippingRate < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/models/webhook_event.rb
class WebhookEvent < ApplicationRecord
  after_create_commit :process_webhook_event

  private

  def process_webhook_event
    CheckoutSessionProcessingJob.perform_later(self)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  allow_unauthenticated_access only: [ :shop, :show ]
  before_action :product_params, only: [ :create ]

  def shop
    @products = Product.all
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    result = ProductService::Create.call(@product)
    if result.success?
      flash[:success] = "Product was successfully created."  # FLASH NOT WORKING IN TURBO FRAME
      redirect_to new_product_path
    else
      flash.now[:danger] = result.errors.join(", ") # FLASH NOT WORKING IN TURBO FRAME
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path, notice: "Product #{@product.title} was updated."
    else
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy!
    redirect_to admin_path, success: "Product was successfully deleted."
  end

  private

  def product_params
    params.expect(product: [ :title, :category, :description, :price, :stock, :main_image, images: [] ])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/helpers/shipping_helper.rb
module ShippingHelper
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/products/_images_preview.html.erb
<!-- app/views/products/_images_preview.html.erb

  Image uploads with previews

-->
<div class="mb-3" data-controller="previews">
  <%= form.label :main_image, class: "form-label" %>
  <%= form.file_field :main_image, class: "form-control",
        direct_upload: true,
        data: { previews_target: "input", action: "change->previews#preview" } %>

  <div class="container mt-2" data-previews-target="preview">
    <% if product.main_image.attached? %>
      <%= image_tag product.main_image.variant(:thumb) %>
    <% end %>
  </div>
</div>

<div class="mb-3" data-controller="previews">
  <%= form.label :images, class: "form-label" %>
  <%= form.file_field :images, multiple: true, class: "form-control", data: { previews_target: "input", action: "change->previews#preview" } %>

  <div class="container mt-2" data-previews-target="preview">
    <% if product.images.attached? %>
      <% product.images.each do |image| %>
        <%= image_tag image.variant(:thumb), data: { previews_target: "preview" } %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/products/_product_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <%= form_with model: product do |form| %>
        <div class="mb-3 d-flex gap-5">

          <div>
            <%= form.label :title, class: "form-label" %>
            <%= form.text_field :title, class: "form-control" %>
          </div>

          <div class="d-flex flex-column">
            <%= form.label :category, class: "form-label" %>
            <%= form.select :category, [["Drinkware", "drinkware"], ["Dinnerware", "dinnerware"], ["Decorative", "decorative"]], {}, { class: "form-select bg-white" } %>
          </div>

        </div>
        <div class="mb-3">
          <%= form.label :description, class: "form-label" %>
          <%= form.text_area :description, class: "form-control", rows: "5" %>
        </div>
        <div class="mb-3">
          <%= form.label :price, class: "form-label" %>
          <%= form.number_field :price, step: :any, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.label :stock, class: "form-label" %>
          <%= form.number_field :stock, class: "form-control" %>
        </div>
        <%= render "images_preview", form: form, product: product %>
        <div class="d-flex justify-content-between mb-5">
          <%= form.submit class: "btn btn-warning" %>
      <% end %>
        <% if !product.id.nil? %>
          <%= button_to "Delete Product", product_path(product.id), class: "btn btn-danger", method: :delete %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<%= turbo_frame_tag id="adminOptions" do %>
  <%= render partial: "layouts/alert" %>
  <h1 style="text-align:center">Edit Product</h1>
  <%= render "product_form", product: @product %>
<% end %>

app/views/products/index.html.erb
<%= turbo_frame_tag id="adminOptions" do %>
  <h1 class="text-center">Products</h1>
  <div class="overflow-scroll" style="height: 800px">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Title</th>
          <th scope="col">Price</th>
          <th scope="col">Stock</th>
        </tr>
      </thead>
      <tbody>
        <% if @products.any? %>
          <%@products.each do |product| %>
            <tr>
              <th scope="row"><%= product.id %></th>
              <td><%= link_to "#{product.title}", edit_product_path(product.id), data: {turbo_frame: "adminOptions" } %></td>
              <td><%= product.price %></td>
              <td><%= product.stock %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/products/new.html.erb
<%= turbo_frame_tag id="adminOptions" do %>
  <%= render partial: "layouts/alert" %>
<h1 style="text-align: center" class="mt-2">New Product</h1>

<%= render "product_form", product: @product %>
<% end %>