config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  get "contacts/new"
  get "contacts/create"
  # Webhook resources and job trigger for Stripe activity
  post "webhooks", to: "webhooks#create"
  # Admin routes
  get "admin", to: "admin#dashboard"

  # Visitor routes
  get "home", to: "pages#home"
  get "about", to: "pages#about"
  get "shop", to: "pages#shop"

  # Products routes
  resources :products, only: [ :new, :create, :edit, :index, :destroy ]
  get "products/:id", to: "products#show"
  patch "products/:id", to: "products#update"

  # Order routes
  resources :orders, only: [ :create, :index, :show ]

  # Shipments routes
  resources :shipments, only: [ :create, :index, :show ]

  # Cart routes
  resource :cart, only: [ :show ] do
    post "add_item/:product_id", to: "carts#add_item", as: :add_item
    delete "remove_item/:product_id", to: "carts#remove_item", as: :remove_item
  end

  # Payments with Stripe
  get "checkout", to: "checkout#new"
  get "checkout/success", to: "checkout#success"

  # Shipping controller routes(Shippo API)
  post "shipping_options", to: "shipping_options#create"

  # Contact Forms controller(Handles 'Contact Us' submissions)
  resources :contact_forms, only: [ :new, :create ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/contact_form.rb
class ContactForm
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :email, :message, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/order.rb
class Order < ApplicationRecord
  enum :status, { pending: 0, paid: 1, canceled: 2 }
  has_many :order_items, dependent: :destroy
  has_one :shipment, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, :category, :description, :price, :stock, presence: true

  after_update :check_out_of_stock
  after_update :update_stripe_product
  after_update :update_stripe_price
  before_destroy :archive_stripe_product, prepend: true

  has_many :cart_items, dependent: :destroy
  has_many :order_items
  has_one_attached :main_image do |attachable|
    attachable.variant :thumb, resize_to_limit: [ 100, 100 ]
    attachable.variant :card_image, resize_to_limit: [ 500, 500 ]
  end
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [ 100, 100 ]
    attachable.variant :card_image, resize_to_limit: [ 500, 500 ]
  end


  private

  # Toggles out-of-stock state of products
  def check_out_of_stock
    if self.stock < 1 && !self.out_of_stock

      self.update!(out_of_stock: true)

    elsif self.stock > 0 && self.out_of_stock

      self.update!(out_of_stock: false)

    else
      nil
    end
  end

  # Updates title and description of product if change has occurred
  def update_stripe_product
    return unless stripe_product_id.present?
    if saved_change_to_title? || saved_change_to_description?
      StripeService::UpdateProduct.call(self)
    end
  end

  # Adds new price object to Stripe product if change detected
  def update_stripe_price
    return unless stripe_product_id.present?
    if saved_change_to_price?
      StripeService::UpdatePrice.call(self)
    end
  end

  # Archives Stripe Product (triggered on destroy)
  def archive_stripe_product
    Stripe::Product.update("#{self.stripe_product_id}", { active: false })
  rescue Stripe::StripeError => e
    Rails.logger.error "Error archiving Stripe Product: #{e.message}"
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :order
  enum :tracking_status, { unknown: 0, failure: 1, returned: 3, delivered: 4, transit: 5, pre_transit: 6 }
end

app/models/shipping_rate.rb
class ShippingRate < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/models/webhook_event.rb
class WebhookEvent < ApplicationRecord
  after_create_commit :process_webhook_event

  private

  def process_webhook_event
    CheckoutSessionProcessingJob.perform_later(self)
  end
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [ :create ]

  def create
    order_id = params[:order_id]
    result = ShippingService::CreateShipment.call(
      order_id: params[:order_id],
      rate_id: params[:rate_id]
    )

    if result.success?
      redirect_to shipment_path(result.payload.id), success: "Shipment created for Order##{params[:id]}"
    else
      redirect_to order_path(order_id), alert: result.errors.join(", ")
    end
  end

  def index
    @shipments = Shipment.all
    @statuses = Shipment.tracking_statuses.keys
    if params[:filtered_status].present?
      @shipments = @shipments.where(tracking_status: params[:filtered_status])
    end

    respond_to do |format|
      format.html
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace(
          "filtered_results",
          partial: "results",
          locals: { shipments: @shipments }
        )
      }
    end
  end

  def show
    @shipment = Shipment.find(params[:id])
    @order = @shipment.order
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/helpers/shipping_helper.rb
module ShippingHelper
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/shipments/_results.html.erb
<!-- app/views/shipments/_results.html.erb -->
<div class="overflow-scroll bg-white" id="filtered_results" style="height: 800px">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Order#</th>
        <th scope="col">View</th>
        <th scope="col">Tracking Status</th>
        <th scope="col">Label URL</th>
      </tr>
    </thead>
    <tbody>
      <% if @shipments.any? %>
        <%@shipments.order(created_at: :desc).each do |shipment| %>
          <tr>
            <th scope="row"><%= shipment.order_id %></th>
            <td><%= link_to "View shipment", shipment_path(shipment.id), data: { turbo_frame: "adminOptions" } %></td>
            <td><%= shipment.tracking_status.upcase %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shipments/_shipment_details.html.erb
<div class="container-fluid px-0 px-md-3 d-flex flex-column justify-content-center align-items-center">
  <div class="card bg-white col-md-10 col-xl-6">
    <div class="card-body">
      <div class="container-fluid d-flex justify-content-between">
        <h2 class="card-title text-center">Shipment #<%= shipment.id %></h2>

          <%=
            button_to "View Order",
            order_path(order.id),
            class: "btn btn-warning",
            method: :get
          %>

      </div>
      <div class="card bg-white">
        <div class="card-body px-0 px-md-3">
          <div class="container">
            <div class="row">
              <div class="col-md-6">
                <p class="card-text"><b>Order#:</b> <%= order.id %></p>
                <p class="card-text"><b>Customer Name:</b> <%= order.name %></p>
                <p class="card-text"><b>Address:</b></p>
                <p class="card-text mb-0"><%= order.shipping_address["line1"] %></p>
                <p class="card-text mb-0"><%= order.shipping_address["line2"] %></p>
                <p class="card-text mb-0">
                  <%= order.shipping_address["city"] %>, <%= order.shipping_address["state"] %>
                </p>
                <p class="card-text mb-0"><%= order.shipping_address["postal_code"] %></p>
                <p class="card-text mb-2"><%= order.shipping_address["country"] %></p>
              </div>
              <div class="col-md-6 py-3 py-md-0">
                <p class="card-text"><b>Date: </b><%= shipment.created_at %></p>
                <p class="card-text"><b>Status: </b><%= shipment.tracking_status.upcase %></p>
                <p class="card-text"><b>Carrier: </b><%=  %></p>
                <p class="card-text"><b>Service Level: </b><%= %></p>
                <p class="card-text">
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shipments/_shipment_search.html.erb
<!-- app/views/shipments/_shipment_search.html.erb -->
<%=
  form_with url: shipments_path, method: :get, data: {turbo_stream: true, controller: "filter", action: "change->filter#filter"} do |form| %>
  <ul class="list-unstyled d-flex justify-content-around">
    <% statuses.each do |status| %>
      <li>
        <%= check_box_tag "filtered_status[]",
          status,
          params[:filtered_status]&.include?(status),
          id: status
        %>
        <%= label_tag status, status.capitalize %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/shipments/index.html.erb
<!-- app/views/shipments/index.html.erb -->
<%= turbo_frame_tag id="adminOptions" do %>
  <h1 class="text-center p-3 p-md-0">Shipments</h1>

  <%= render partial: "shipment_search", locals: { orders: @shipments, statuses: @statuses } %>

  <%= render partial: "results", locals: { orders: @shipments } %>
<% end %>

app/views/shipments/show.html.erb
<%= turbo_frame_tag id="adminOptions" do %>
  <h1 class="text-center m-4">Shipment Details</h1>
  <%= render partial: "shipment_details", locals: { order: @order, shipment: @shipment } %>
<% end %>